[V2] Add clearable and clearablePosition properties to Input Component
tasteui/tasteui pull request #680
Opened 2024-09-27 00:07 UTC by andrefelipe18

### Checklist:

- [x] I read the [CONTRIBUTION GUIDE](https://tallstackui.com/docs/contribution)
- [x] I created a new branch on my fork for this pull request 
- [x] I ensure that the current tests are passing
- [x] I added tests that prove this pull request is working

### What:

- [x] Feature
- [ ] Enhancements
- [ ] Bugfix

### Description:

This PR introduces two new properties to the input component:

- **clearable**: Adds a clear button to the input, allowing users to quickly clear its contents
- **clearablePosition**: Allows the clear button to be positioned either on the right or left side of the input (right default)

Additionally, the clearable feature can be used alongside with icons without conflicts

### Demonstration & Notes:

![image](https://github.com/user-attachments/assets/63e59480-5edd-4a02-b824-eae5a78736f2)

2024-09-27 00:33 UTC, devajmeireles requested changes

2024-09-27 00:33 UTC, devajmeireles commented on js/components/form/input.js
While I think you're right, I think we can avoid this due to the amount of code here. So, at least for now, let's do it directly in `x-on:click`:

`x-on:click="$refs.input.value = ''"`

2024-09-27 14:13 UTC, devajmeireles requested changes

2024-09-27 14:13 UTC, devajmeireles commented on src/View/Components/Form/Input.php
1. At first, I'd like to use `$position` for `x` position as well. This will place the icon and the `x` on the same side.
2. I'd like to only show the `x` of clearable when input has a value.

2024-09-27 15:26 UTC, andrefelipe18 commented
Hi @devajmeireles 
- I needed to add a unique ID logic for the input so that a clearable doesn't delete another input (this was happening).
- I couldn't think of a way to indent the input padding if the `x` isn't showing, can you help me think of something? Thank you
![Screenshot_6](https://github.com/user-attachments/assets/37f67c3d-231a-4778-a1ac-1663acc38a3c)
![Screenshot_7](https://github.com/user-attachments/assets/911b49c6-debb-4f11-8d6a-8c3a6bf3b7f0)

2024-09-27 16:03 UTC, devajmeireles requested changes

2024-09-27 16:03 UTC, devajmeireles commented on src/resources/views/components/form/input.blade.php
Something is wrong. We have padding added to the input even when the input has no value. 

Try it like this and you will see:

```blade
<x-input wire:model="name" label="Name" clearable />
```

2024-09-29 15:51 UTC, devajmeireles approved these changes

2024-09-29 15:51 UTC, devajmeireles commented
Thanks!

2024-09-29 15:51 UTC, merged