[V2] Accept null values in color input
tasteui/tasteui pull request #699
Opened 2024-10-03 13:52 UTC by andrefelipe18

### Checklist:

- [x] I read the [CONTRIBUTION GUIDE](https://tallstackui.com/docs/contribution)
- [x] I created a new branch on my fork for this pull request 
- [x] I ensure that the current tests are passing
- [WIP] I added tests that prove this pull request is working 

### What:

- [ ] Feature
- [x] Enhancements
- [ ] Bugfix

### Description:

Add new **clear** button in color input

### Demonstration & Notes:

https://github.com/user-attachments/assets/b56a99d6-acff-4517-835d-d067dc77ae0f

2024-10-03 16:37 UTC, devajmeireles requested changes

2024-10-03 16:37 UTC, devajmeireles commented on js/components/form/color.js
> +    this.model = '#';
Isn't it to be set as null?

2024-10-03 16:37 UTC, devajmeireles commented on tests/Browser/Form/ColorTest.php
> +    public function can_open_select_a_color_and_clear_it(): void
Since the `clearable` element is only visible when the value is filled, would be useful to have a test to validate that the `clearable` element is visible.

2024-10-03 17:07 UTC, andrefelipe18 commented on tests/Browser/Form/ColorTest.php
> +    public function can_open_select_a_color_and_clear_it(): void
good ideia, i will implement in the next commit

2024-10-03 17:08 UTC, andrefelipe18 commented on js/components/form/color.js
> +    this.model = '#';
when set null, dont work with wire:model property

2024-10-04 01:23 UTC, devajmeireles approved these changes

2024-10-04 01:23 UTC, merged