[V2]
tasteui/tasteui pull request #702
Opened 2024-10-05 13:49 UTC by andrefelipe18

### Checklist:

- [x] I read the [CONTRIBUTION GUIDE](https://tallstackui.com/docs/contribution)
- [x] I created a new branch on my fork for this pull request 
- [x] I ensure that the current tests are passing
- [no] I added tests that prove this pull request is working

### What:

- [x] Feature
- [ ] Enhancements
- [ ] Bugfix

### Description:

Adds new property **$group** to accept groups of values (https://primevue.org/select/#group)

### Demonstration & Notes:

<details>
  <summary>Blade</summary>

   ```blade
     <x-select.styled group :options="[
        [
            'label' => 'Brazil',
            'image' => 'https://placehold.co/15x15/cyan/white',
            'description' => 'Brazilian Real',
            'value' => [
                ['label' => 'São Paulo', 'value' => 4, 'image' => 'https://placehold.co/15x15/orange/white'],
                ['label' => 'Rio de Janeiro', 'value' => 5, 'image' => 'https://placehold.co/15x15/orange/white'],
                ['label' => 'Brasília', 'value' => 6, 'image' => 'https://placehold.co/15x15/orange/white']
            ]
        ],
        [
            'label' => 'Japan',
            'image' => 'https://placehold.co/15x15/yellow/white',
            'value' => [
                ['label' => 'Tokyo', 'value' => 1, 'image' => 'https://placehold.co/15x15/red/white'],
                ['label' => 'Kyoto', 'value' => 2, 'image' => 'https://placehold.co/15x15/red/white'],
                ['label' => 'Osaka', 'value' => 3, 'image' => 'https://placehold.co/15x15/red/white']
            ]
        ],
        [
            'label' => 'United States',
            'image' => 'https://placehold.co/15x15/purple/white',
            'value' => [
                ['label' => 'New York', 'value' => 7, 'image' => 'https://placehold.co/15x15/blue/white'],
                ['label' => 'Los Angeles', 'value' => 8, 'image' => 'https://placehold.co/15x15/blue/white'],
                ['label' => 'Chicago', 'value' => 9, 'image' => 'https://placehold.co/15x15/blue/white']
            ]
        ],
        [
            'label' => 'Germany',
            'image' => 'https://placehold.co/15x15/pink/white',
            'value' => [
                ['label' => 'Berlin', 'value' => 10, 'image' => 'https://placehold.co/15x15/green/white'],
                ['label' => 'Munich', 'value' => 11, 'image' => 'https://placehold.co/15x15/green/white'],
                ['label' => 'Hamburg', 'value' => 12, 'image' => 'https://placehold.co/15x15/green/white']
            ]
        ],
    ]" />
   ```
</details>

https://github.com/user-attachments/assets/eeae2bc9-d855-4f23-b307-1431b8725ba1

2024-10-05 14:59 UTC, devajmeireles commented on src/View/Components/Select/Styled.php
> +        public ?bool $group = false,
Rename this to `$grouped`

2024-10-05 15:00 UTC, devajmeireles requested changes

2024-10-05 15:00 UTC, devajmeireles commented on src/View/Components/Select/Styled.php
> +        public ?bool $group = false,
Rename this to `$grouped`

2024-10-05 15:00 UTC, devajmeireles commented on src/resources/views/components/select/styled.blade.php
> +                @if($group)
```suggestion
                @if ($group)
```

2024-10-05 23:20 UTC, devajmeireles commented
We're on the right track for that! Lastly, I'd love to see padding on all items in the group. Something very basic, like:

```
Brazil
  São Paulo
  Bahia
US
  California
  Texas
```

2024-10-24 02:59 UTC, devajmeireles commented
Hey, @andrefelipe18 ! This looks amazing! Can you proceed with this PR? We only need one fix, I can handle all the other improvements that are needed.

We need to fix the parent-related text, because it is black, whether in light or dark mode:
![CleanShot 2024-10-23 at 23 58 49](https://github.com/user-attachments/assets/1ad6bc80-0938-4666-b65a-cb1f6cc5692d)

2024-10-24 09:45 UTC, andrefelipe18 commented
![image](https://github.com/user-attachments/assets/ec392b9f-f6fe-41c1-ba86-c8527e76dbc2)

2024-10-24 14:16 UTC, devajmeireles approved these changes

2024-10-24 14:44 UTC, devajmeireles approved these changes

2024-10-24 14:45 UTC, devajmeireles commented
Thanks, @andrefelipe18 !

2024-10-24 14:45 UTC, merged